MINIMUM_PERIOD = 15
PERIOD_STEPS = 60/MINIMUM_PERIOD

# SEARCH OPTIONS
RADIUS_LIST = [1, 2, 3, 5, 10, 25]
DEFAULT_RADIUS = 3
ORDERING_LIST = ['hype', 'rating', 'price']
DEFAULT_ORDERING = 'rating'
TYPE_LIST = ['all', 'premium', 'public']
DEFAULT_TYPE = 'premium'

PRICE_WEIGHT = 1
SCORE_WEIGHT = 10
VOTES_WEIGHT = 5
VIEWS_WEIGHT = 3

FEEDBACK_ITEMS = 20
FEEDBACK_TUTOR_DETAIL_ITEMS = 10

# BOOKING
UNIVERSAL_FEE = 0.2 # 0.2 represents 20%
