# TIME
MINIMUM_PERIOD = 15
PERIOD_STEPS = 60/MINIMUM_PERIOD
STOP_WINDOW = 3 # in minutes


# SEARCH OPTIONS
PRICE_WEIGHT = 1
SCORE_WEIGHT = 10
VOTES_WEIGHT = 5
VIEWS_WEIGHT = 3

# FEEDBACK
FEEDBACK_ITEMS = 20
FEEDBACK_TUTOR_DETAIL_ITEMS = 10

# BOOKING
UNIVERSAL_FEE = 0.2 # 0.2 represents 20%


# CREDITS
CREDIT_VALUE = 1.0 # 1 CREDIT IN GBP (float value)


# TUTOR SUBJECTS
MINIMUM_CREDITS_PER_HOUR = 10


# WITHDRAW COMMISSIONS
COMMISSION_WITHDRAW_FIXED = 0
COMMISSION_WITHDRAW_PERCENTAGE = 0.01 # represents 5%


